apiVersion: apps/v1
kind: Deployment
metadata:
  name: derivco-missconfig
  labels:
    app: derivco-missconfig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: derivco-missconfig
  template:
    metadata:
      labels:
        app: derivco-missconfig
    spec:
      containers:
      - name: derivco-missconfig
        image: nginx
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "10m"
            memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
 name: derivco-missconfig-service
spec:
 selector:
   app: derivco-missconfig
 ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080